package com.zb.blog.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;

/**
 * blog
 * 
 * @author bianj
 * @version 1.0.0 2020-08-24
 */

@ApiModel("博客")
@Data@AllArgsConstructor@NoArgsConstructor
public class Blog implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 5868057162640894203L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @ApiModelProperty("博客id")
    private Integer id;

    /** userId */
    @ApiModelProperty("博主id")
    private Integer userId;

    /** userObj */
    @ApiModelProperty("博主对象")
    private User userObj;

    /** property */
    @ApiModelProperty("博客性质(1：原创  2：转载  3：翻译)")
    private Integer property;

    /** title */
    @ApiModelProperty("博客标题")
    private String title;

    /** blogAbstract */
    @ApiModelProperty("博客简介")
    private String blogAbstract;

    /** content */
    @ApiModelProperty("博客内容")
    private String content;

    /** publishTime */
    @ApiModelProperty("博客发布时间")
    private Date publishTime;

    /** pageViewCount */
    @ApiModelProperty("博客浏览数")
    private Integer pageViewCount;

    /** tag */
    @ApiModelProperty("博客的标签id")
    private String tag;

    /** tagObj */
    private List<Tag> tagObj;

    /** sort */
    @ApiModelProperty("博客所属的分类id")
    private String sort;

    /** sortObj */
    private Sort sortObj;

    public List<Tag> getTagObj() {
        return tagObj;
    }

    /** blogComment */
    @ApiModelProperty("博客评论")
    private String blogComment;

    /** blogImg */
    @ApiModelProperty("博客首页图片地址")
    private String blogImg;

    /** blogState */
    @ApiModelProperty("博客状态(-1：已删除 0：未发布 1：已发布)")
    private Integer blogState;

    /** likeState */
    @ApiModelProperty("博客是否可以赞赏")
    private Integer likeState;

    /** commentState */
    @ApiModelProperty("博客是否可以评论")
    private Integer commentState;

    /** recommendState */
    @ApiModelProperty("博客是否可以推荐")
    private Integer recommendState;

    /** reprintState */
    @ApiModelProperty("博客是否可以转载")
    private Integer reprintState;

    /** createTime */
    @ApiModelProperty("博客创建时间")
    private Date createTime;

    /** updateTime */
    @ApiModelProperty("博客修改时间")
    private Date updateTime;
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取title
     * 
     * @return title
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * 设置title
     * 
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 获取blogAbstract
     * 
     * @return blogAbstract
     */
    public String getBlogAbstract() {
        return this.blogAbstract;
    }

    /**
     * 设置blogAbstract
     * 
     * @param blogAbstract
     */
    public void setBlogAbstract(String blogAbstract) {
        this.blogAbstract = blogAbstract;
    }

    /**
     * 获取content
     * 
     * @return content
     */
    public String getContent() {
        return this.content;
    }

    /**
     * 设置content
     * 
     * @param content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取publishTime
     * 
     * @return publishTime
     */
    public Date getPublishTime() {
        return this.publishTime;
    }

    /**
     * 设置publishTime
     * 
     * @param publishTime
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * 获取pageViewCount
     * 
     * @return pageViewCount
     */
    public Integer getPageViewCount() {
        return this.pageViewCount;
    }

    /**
     * 设置pageViewCount
     * 
     * @param pageViewCount
     */
    public void setPageViewCount(Integer pageViewCount) {
        this.pageViewCount = pageViewCount;
    }

    /**
     * 获取tag
     * 
     * @return tag
     */
    public String getTag() {
        return this.tag;
    }

    /**
     * 设置tag
     * 
     * @param tag
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * 获取sort
     * 
     * @return sort
     */
    public String getSort() {
        return this.sort;
    }

    /**
     * 设置sort
     * 
     * @param sort
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * 获取blogComment
     * 
     * @return blogComment
     */
    public String getBlogComment() {
        return this.blogComment;
    }

    /**
     * 设置blogComment
     * 
     * @param blogComment
     */
    public void setBlogComment(String blogComment) {
        this.blogComment = blogComment;
    }

    /**
     * 获取blogImg
     * 
     * @return blogImg
     */
    public String getBlogImg() {
        return this.blogImg;
    }

    /**
     * 设置blogImg
     * 
     * @param blogImg
     */
    public void setBlogImg(String blogImg) {
        this.blogImg = blogImg;
    }

    /**
     * 获取blogState
     * 
     * @return blogState
     */
    public Integer getBlogState() {
        return this.blogState;
    }

    /**
     * 设置blogState
     * 
     * @param blogState
     */
    public void setBlogState(Integer blogState) {
        this.blogState = blogState;
    }

    /**
     * 获取likeState
     * 
     * @return likeState
     */
    public Integer getLikeState() {
        return this.likeState;
    }

    /**
     * 设置likeState
     * 
     * @param likeState
     */
    public void setLikeState(Integer likeState) {
        this.likeState = likeState;
    }

    /**
     * 获取commentState
     * 
     * @return commentState
     */
    public Integer getCommentState() {
        return this.commentState;
    }

    /**
     * 设置commentState
     * 
     * @param commentState
     */
    public void setCommentState(Integer commentState) {
        this.commentState = commentState;
    }

    /**
     * 获取recommendState
     * 
     * @return recommendState
     */
    public Integer getRecommendState() {
        return this.recommendState;
    }

    /**
     * 设置recommendState
     * 
     * @param recommendState
     */
    public void setRecommendState(Integer recommendState) {
        this.recommendState = recommendState;
    }

    /**
     * 获取reprintState
     * 
     * @return reprintState
     */
    public Integer getReprintState() {
        return this.reprintState;
    }

    /**
     * 设置reprintState
     * 
     * @param reprintState
     */
    public void setReprintState(Integer reprintState) {
        this.reprintState = reprintState;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    /* This code was generated by TableGo tools, mark 2 end. */
}