package com.zb.blog.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * comment
 * 
 * @author bianj
 * @version 1.0.0 2020-08-24
 */
@ApiModel("博客评论")
@Data@AllArgsConstructor@NoArgsConstructor
public class Comment implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4684978247907686746L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @ApiModelProperty("评论id")
    private Integer id;

    /** commentPersonName */
    @ApiModelProperty("评论人的名字")
    private String commentPersonName;

    /** commentPersonId */
    @ApiModelProperty("评论人id")
    private Integer commentPersonId;

    /** user */
    @ApiModelProperty("评论人对象")
    private User user;

    /** blogId */
    @ApiModelProperty("所属的博客id")
    private Integer blogId;

    /** blogTitle */
    @ApiModelProperty("所属的博客标题")
    private String blogTitle;

    /** blogObj */
    private Integer blogObj;

    /** publishTime */
    @ApiModelProperty("审核通过后的发布时间")
    private Date publishTime;

    /** bloggerState */
    @ApiModelProperty("是不是博主(0：不是 1：是)")
    private Integer bloggerState;

    /** commentState */
    @ApiModelProperty("评论状态(-1：已删除  0：审核未通过 1：审核已通过 )")
    private Integer commentState;

    /** content */
    @ApiModelProperty("评论内容")
    private String content;

    /** parentId */
    @ApiModelProperty("父评论id")
    private Integer parentId;

    /** createTime */
    @ApiModelProperty("评论时间")
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取commentPersonName
     * 
     * @return commentPersonName
     */
    public String getCommentPersonName() {
        return this.commentPersonName;
    }

    /**
     * 设置commentPersonName
     * 
     * @param commentPersonName
     */
    public void setCommentPersonName(String commentPersonName) {
        this.commentPersonName = commentPersonName;
    }

    /**
     * 获取commentPersonId
     * 
     * @return commentPersonId
     */
    public Integer getCommentPersonId() {
        return this.commentPersonId;
    }

    /**
     * 设置commentPersonId
     * 
     * @param commentPersonId
     */
    public void setCommentPersonId(Integer commentPersonId) {
        this.commentPersonId = commentPersonId;
    }

    /**
     * 获取blogId
     * 
     * @return blogId
     */
    public Integer getBlogId() {
        return this.blogId;
    }

    /**
     * 设置blogId
     * 
     * @param blogId
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * 获取publishTime
     * 
     * @return publishTime
     */
    public Date getPublishTime() {
        return this.publishTime;
    }

    /**
     * 设置publishTime
     * 
     * @param publishTime
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * 获取bloggerState
     * 
     * @return bloggerState
     */
    public Integer getBloggerState() {
        return this.bloggerState;
    }

    /**
     * 设置bloggerState
     * 
     * @param bloggerState
     */
    public void setBloggerState(Integer bloggerState) {
        this.bloggerState = bloggerState;
    }

    /**
     * 获取commentState
     * 
     * @return commentState
     */
    public Integer getCommentState() {
        return this.commentState;
    }

    /**
     * 设置commentState
     * 
     * @param commentState
     */
    public void setCommentState(Integer commentState) {
        this.commentState = commentState;
    }

    /**
     * 获取content
     * 
     * @return content
     */
    public String getContent() {
        return this.content;
    }

    /**
     * 设置content
     * 
     * @param content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取parentId
     * 
     * @return parentId
     */
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * 设置parentId
     * 
     * @param parentId
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}