package com.zb.blog.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * sort
 * 
 * @author bianj
 * @version 1.0.0 2020-08-24
 */
@ApiModel("分类")
@Data@AllArgsConstructor@NoArgsConstructor
public class Sort implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -4525798595423697322L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @ApiModelProperty("分类id")
    private Integer id;

    /** sortName */
    @ApiModelProperty("分类名")
    private String sortName;

    /** sortAbstract */
    @ApiModelProperty("分类简介")
    private String sortAbstract;

    /** blogCount */
    @ApiModelProperty("该分类下的博客数")
    private Integer blogCount;

    /** sortState */
    @ApiModelProperty("分类状态(0：使用中  -1：已删除)")
    private Integer sortState;

    /** createTime */
    @ApiModelProperty("分类创建时间")
    private Date createTime;

    /** updateTime */
    @ApiModelProperty("分类的修改时间")
    private Date updateTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取sortName
     * 
     * @return sortName
     */
    public String getSortName() {
        return this.sortName;
    }

    /**
     * 设置sortName
     * 
     * @param sortName
     */
    public void setSortName(String sortName) {
        this.sortName = sortName;
    }

    /**
     * 获取sortAbstract
     * 
     * @return sortAbstract
     */
    public String getSortAbstract() {
        return this.sortAbstract;
    }

    /**
     * 设置sortAbstract
     * 
     * @param sortAbstract
     */
    public void setSortAbstract(String sortAbstract) {
        this.sortAbstract = sortAbstract;
    }

    /**
     * 获取blogCount
     * 
     * @return blogCount
     */
    public Integer getBlogCount() {
        return this.blogCount;
    }

    /**
     * 设置blogCount
     * 
     * @param blogCount
     */
    public void setBlogCount(Integer blogCount) {
        this.blogCount = blogCount;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getSortState() {
        return sortState;
    }

    public void setSortState(Integer sortState) {
        this.sortState = sortState;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}