package com.zb.blog.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * tag
 * 
 * @author bianj
 * @version 1.0.0 2020-08-24
 */
@ApiModel("标签")
public class Tag implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1196246331375589851L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @ApiModelProperty("标签id")
    private Integer id;

    /** tagName */
    @ApiModelProperty("标签名")
    private String tagName;

    /** blogCount */
    @ApiModelProperty("该标签下的博客数")
    private Integer blogCount;

    /** tagState */
    @ApiModelProperty("标签状态(0：使用中 -1：已删除)")
    private Integer tagState;

    /** createTime */
    @ApiModelProperty("标签创建时间")
    private Date createTime;

    /** updateTime */
    @ApiModelProperty("标签更改时间")
    private Date updateTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取tagName
     * 
     * @return tagName
     */
    public String getTagName() {
        return this.tagName;
    }

    /**
     * 设置tagName
     * 
     * @param tagName
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * 获取blogCount
     * 
     * @return blogCount
     */
    public Integer getBlogCount() {
        return this.blogCount;
    }

    /**
     * 设置blogCount
     * 
     * @param blogCount
     */
    public void setBlogCount(Integer blogCount) {
        this.blogCount = blogCount;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getTagState() {
        return tagState;
    }

    public void setTagState(Integer tagState) {
        this.tagState = tagState;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}