package com.zb.blog.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * user
 * 
 * @author bianj
 * @version 1.0.0 2020-08-24
 */
@ApiModel("用户")
@Data
@AllArgsConstructor@NoArgsConstructor
public class User implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 8120957201697904258L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @ApiModelProperty("用户id")
    private Integer id;

    /** username */
    @ApiModelProperty("用户名")
    private String username;

    /** password */
    @ApiModelProperty("用户密码")
    private String password;

    /** managerState */
    @ApiModelProperty("该用户是否是管理员(0：不是  1：是)")
    private Integer managerState;

    /** icon */
    @ApiModelProperty("用户头像地址")
    private String icon;

    public User(String username, String password, Integer managerState, String icon) {
        this.username = username;
        this.password = password;
        this.managerState = managerState;
        this.icon = icon;
    }

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取username
     * 
     * @return username
     */
    public String username() {
        return this.username;
    }

    /**
     * 设置username
     * 
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * 获取password
     * 
     * @return password
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * 设置password
     * 
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 获取managerState
     * 
     * @return managerState
     */
    public Integer getManagerState() {
        return this.managerState;
    }

    /**
     * 设置managerState
     * 
     * @param managerState
     */
    public void setManagerState(Integer managerState) {
        this.managerState = managerState;
    }

    /**
     * 获取icon
     * 
     * @return icon
     */
    public String getIcon() {
        return this.icon;
    }

    /**
     * 设置icon
     * 
     * @param icon
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}